---
name: PowerShell Lint

on:
  push:
    paths:
      - '**.ps1'

jobs:
  lint:
    name: Lint
    timeout-minutes: 3
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.1-preview.3+3453
      - name: Setup Analyzer
        run: choco install psscriptanalyzer
      - name: Analyze
        shell: pwsh
        run: .\powershell-lint.ps1
