---
name: YAML Lint

on:
  push:
    paths:
      - '**.yml'

jobs:
  lint:
    name: Lint
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: ibiqlik/action-yamllint@v1.0.0
        with:
          config_file: .yamllint.yml
          strict: false
          file_or_dir: .yamllint.yml .github/**.yml
